### ISSUE TITLE
Правки по модулю openweatherApi 

### ISSUE THREAD

**Issue by mitisit89** [basher-balance/my_ethernet#3]
https://github.com/basher-balance/my_ethernet/blob/a0c899bb887ea3fab028d29b5d6925ffe96feefd/task_scheduler/weather_periodic_tasks.py#L12-L82
 Ты можешь указать при запросе к апи количество дней (в unix формате) которое нужно daily.dt и исключить ненужные данные с помощью exclude 
Можно запрашивать данные в одном запросе 
https://openweathermap.org/api/one-call-api подробнее здесь

**Comment by basher-balance** [comment]
я об этом думал, но данные, которые приходят за неделю, там не полная информация, поэтому я делаю 2 запроса. 1 на текущий день с полной картиной и на неделю или сколько там не помню

**Comment by basher-balance** [comment]
точно не помню, но у меня там вроде 2 запроса. 1 из которых почасовой, который берет текущие данные о погоде, которые самые последние на сегодня. 2 запрос данные на неделю. Думаю так точнее будет, плюс если выгружать текущие данные из 1 запроса, там данных больше: погода утром, вечером, на кануне... не путать с мин-макс- средняя

**Comment by basher-balance** [comment]
или я что то не понял

**Comment by mitisit89** [comment]
> точно не помню, но у меня там вроде 2 запроса. 1 из которых почасовой, который берет текущие данные о погоде, которые самые последние на сегодня. 2 запрос данные на неделю. Думаю так точнее будет, плюс если выгружать текущие данные из 1 запроса, там данных больше: погода утром, вечером, на кануне... не путать с мин-макс- средняя

Так openweather api , позволяет  получить все в одном запросе

**Comment by basher-balance** [comment]
ну тада сегодня буду копать
